version: '3'
services:
    web:
      stdin_open: true
      build:
         context: .
         dockerfile: Dockerfile.dev        
      ports:
         - "30002:3000"
      volumes:
         - /app/node_modules
         - .:/app